name: Deploy Docusaurus to GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write       # Allows pushing to GitHub Pages
      id-token: write       # Required for authentication with GitHub Pages
      pages: write          # Additional permission needed for Pages deployment

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Ensure this matches Docusaurus requirements

      - name: Clean build directory
        run: rm -rf ./docs/build  # Clears any old build files

      - name: Install dependencies
        working-directory: ./docs
        run: npm install

      - name: Build Docusaurus site
        working-directory: ./docs
        run: npm run build

      - name: Upload build output as artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Name the artifact for GitHub Pages deployment
          path: ./docs/build  # Path to the Docusaurus build output


      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

